### ISSUE TITLE
Endpoint

### ISSUE THREAD

**Issue by idkjs** [lukkaszw/chat-app#1]
Thanks for sharing this.

I am trying learn this elixir thing and would like to run you app.

What endpoint are you using for it?

Thanks again!

**Comment by lukkaszw** [comment]
Sorry, but it was one of the task in the recruitment process so endpoints aren't mine. I am not authorized to share them. I even don't know if they are working still.  You can use this front if you want.

**Comment by idkjs** [comment]
Thanks, brother.
